#!/bin/sh

tty=${PWD##*-}

[ -r conf ] && . ./conf

if [ -x /sbin/agetty -o -x /bin/agetty ]; then
	# util-linux
	GETTY=agetty
elif [ -x /sbin/getty -o -x /bin/getty ]; then
	# busybox
	GETTY=getty
fi

exec setsid ${GETTY} ${GETTY_ARGS} \
	"${tty}" "${BAUD_RATE}" "${TERM_NAME}"
